services:
  app_proxy:
    environment:
      APP_HOST: mrbrown-timescaledb_pgadmin_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
    restart: on-failure
    depends_on:
      - pgadmin
    networks:
      - umbrel_main_network

  timescaledb:
    image: timescale/timescaledb:2.17.2-pg16
    restart: on-failure
    stop_grace_period: 5m
    environment:
      POSTGRES_DB: timescale_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${APP_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${APP_DATA_DIR}/postgresql:/var/lib/postgresql/data
    command: 
      - postgres
      - -c
      - shared_preload_libraries=timescaledb
      - -c
      - max_connections=200
      - -c
      - shared_buffers=256MB
    networks:
      - umbrel_main_network

  pgadmin:
    image: dpage/pgadmin4:8.12
    user: "1000:1000"
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@timescaledb.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ${APP_DATA_DIR}/pgadmin:/var/lib/pgadmin
    depends_on:
      - timescaledb
    networks:
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true