services:
  app_proxy:
    environment:
      APP_HOST: mrbrown-timescaledb_pgadmin_1
      APP_PORT: 9293
      PROXY_AUTH_ADD: "false"
    restart: on-failure
    depends_on:
      - pgadmin
    networks:
      - umbrel_main_network

  timescaledb:
    container_name: mrbrown-timescaledb_timescaledb_1
    image: timescale/timescaledb:2.17.2-pg16
    restart: on-failure
    stop_grace_period: 5m
    environment:
      POSTGRES_DB: timescale_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${APP_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${APP_DATA_DIR}/postgresql:/var/lib/postgresql/data
    command: 
      - postgres
      - -c
      - shared_preload_libraries=timescaledb
      - -c
      - max_connections=200
      - -c
      - shared_buffers=256MB
    networks:
      - umbrel_main_network

  pgadmin:
    image: dpage/pgadmin4:8.12
    restart: on-failure
    user: "0:0"  # temporarily run as root so we can fix perms
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
      PGADMIN_CONFIG_SESSION_DB_PATH: "'/var/lib/pgadmin/sessions'"
    volumes:
      - ${APP_DATA_DIR}/pgadmin:/var/lib/pgadmin
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /var/lib/pgadmin/sessions
        chown -R 5050:5050 /var/lib/pgadmin
        exec /entrypoint.sh
    depends_on:
      - timescaledb
    networks:
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true
